# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gsaint.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None

wandb:
  use: True
  project: gtblueprint
<<<<<<< HEAD
  name_tag: gsaint-arxiv_2023-origin

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  auto_resume: False
  lr: 0.01

model:
  type: gsaint_gae
  out_channels: 16
  hidden_channels: 8  # Assume that the dimension of the hidden layer feature is 8
  in_channels: 500 # Missed! AttrubuteError
    
=======
  name_tag: gsaint-pubmed-origin
  
train:
  mode: custom
  batch_size: 2048
  eval_period: 1
  epochs: 500 #10000
  device: 1
  use_valedges_as_input: True
  lr: 0.01 # {0.1, 0.01, 0.001, 0.0001}
  l2: 0.0
  auto_resume: False
  finetune: False

  
model:
  type: GAE # Here you can paste different name of model
  sampler: gsaint #None 
  out_channels: 32
  heads: 4
  hidden_channels: 32  # {128, 256, 512}
  in_channels: 1433
  batch_size_sampler: 256
  walk_length: 50
  num_steps: 20
  sample_coverage: 100

>>>>>>> ea92b90a2dc71dd378457a0877c2aab641119c5e
num_threads: 11

data:
  name: pubmed
  undirected: True
<<<<<<< HEAD
  device: 0 
=======
>>>>>>> ea92b90a2dc71dd378457a0877c2aab641119c5e
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
<<<<<<< HEAD
  num_features: 500
  split_index: [0.8, 0.15, 0.05]
=======
  num_features: 1433
  device: 1
  split_index: [0.4, 0.125, 0.025]
>>>>>>> ea92b90a2dc71dd378457a0877c2aab641119c5e

optimizer:
  type: adam
  base_lr: 0.01
  weight_decay: 0.0005
<<<<<<< HEAD
=======

>>>>>>> ea92b90a2dc71dd378457a0877c2aab641119c5e
