out_dir: results
metric_best: acc
cfg_dest: ncnc.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


train:
  mode: custom
  batch_size: 2048 #
  eval_period: 1
  epochs: 100
  device: 0
  auto_resume: False
  final_eval: False
  finetune: False
  dynamic_train: False

model:
  model: puregcn
  type: NCNC
  out_channels: 32
  in_channels: 1433
  hidden_channels: 256
  mplayers: 1
  nnlayers: 3
  ln: True
  lnnn: True
  res: False
  jk: True
  hiddim: 64 #
  gnndp: 0.1 #
  xdp: 0.3 #
  tdp: 0.0 #
  gnnedp: 0.0 #
  predp: 0.05 #
  preedp: 0.0 #


  probscale: 5.0 #
  proboffset: 3.0 #
  pt: 0.05 #


num_threads: 11

wandb:
  use: True
  project: gtblueprint
  name_tag: ncnc-pubmed


data:
  name: pubmed
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433
  device: 0
  split_index: [0.8, 0.15, 0.05]
  max_x: -1
  use_valedges_as_input: True

optimizer:
  type: adam
  gnnlr: 0.01 #
  prelr: 0.005 #
  weight_decay: 0.0005