# line.yaml
out_dir: results
metric_best: acc
cfg_dest: vgae.yaml
print: both
seed: 0
run:
  seed: 0
  num_threads: 11
  multiple_splits: None

wandb:
  use: True
  project: gtblueprint
  name_tag: vgae-cora-origin

train:
  mode: custom
  batch_size: 2**14
  eval_period: 1
  epochs: 200
  device: 0
  auto_resume: False
  final_eval: False
  finetune: False
  
model:
  type: VGAE
  out_channels: 32
  hidden_channels: 32  # Assume that the dimension of the hidden layer feature is 8
    
num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.1
  test_pct: 0.2
  split_labels: True
  num_features:  1433
  device: 0
  split_index: [0.7, 0.1, 0.2]

optimizer:
  type: adam
  base_lr: 0.01
  weight_decay: 0.0005