# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gat.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


wandb:
  use: True
  project: gtblueprint
  name_tag: gat-cora-origin


num_threads: 11

train:
  mode: custom
  batch_size: 2048
  eval_period: 1
  epochs: 2000
  device: 1
  auto_resume: False
  final_eval: False
  finetune: False


model:
  type: GAT
  in_channels: None
  out_channels: 128
  heads: 4
  hidden_channels: 32
  negative_slope: 0.2
  dropout: 0
  num_layers: 2

num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  split_labels: True
  split_index: [0.8, 0.15, 0.05]

optimizer:
  type: adam
  base_lr: 0.001
  weight_decay: 0.0005