# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gae.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None

wandb:
  use: True
  project: gtblueprint
  name_tag: gae-cora-origin

train:
  mode: custom
  batch_size: 1024 
  eval_period: 1
  epochs: 10000
  device: 0
  auto_resume: False
  final_eval: False
  finetune: False

model:
  type: GAE
  out_channels: 32
  in_channels: 1433

num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433
  device: 0
  split_index: [0.8, 0.15, 0.05]

optimizer:
  type: adam
  base_lr: 0.01
  weight_decay: 0.0005
  
llm:
  llm_embedding: True
  batch_size: 4
  model_type: shallow_embedding
  model_name: tfidf
  
embedding_fine_tuning:
    model_name: sentence-transformers/all-mpnet-base-v2 