# line.yaml

out_dir: results
metric_best: [Hits@10, MRR, AUC]
cfg_dest: heart_gnn_models.yaml

run:
  seed: 0
  repeat: 3

train:
  mode: custom
  batch_size: 1024
  eval_period: 1
  epochs: 500
  device: 0
  use_valedges_as_input: True
  lr: 0.001
  l2: 0.0
  runs: 10 
  kill_cnt: 30
  auto_resume: False
  finetune : False

model:
  type: LINKX

  batch_size_sampler: 1024
  Custom_GCN: 
    in_channels: None
    hidden_channels: 32
    out_channels: 32
    negative_slope: 0.1
    dropout: 0
    num_layers: 2

  Custom_GAT:
    heads: 4
    hidden_channels: 32
    negative_slope: 0.1
    dropout: 0
    num_layers: 2
    emb: False
    in_channels: None
    out_channels: 32

  GraphSAGE:
    in_channels: None
    hidden_channels: 64
    out_channels: 128
    num_layers: 2
    dropout: 0
    emb: False

  Custom_GIN:
    out_channels: 64
    hidden_channels: 64
    dropout: 0
    emb: False
    num_layers: 2
    mlp_layer: 1

  LINKX:
    
    hidden_channels: 16         
    out_channels: 1            
    num_layers: 1           
    num_edge_layers: 1         
    num_node_layers: 1       

score:
  type: LinkPredictor

  Custom_GAT:
    score_in_channels: 32 #must be same as out_channels of GAT
    score_hidden_channels: 64
    score_num_layers_predictor: 3
    score_dropout: 0.1
    score_out_channels: 1
    score_gin_mlp_layer: 2
    score_cat_node_feat_mf: False
    score_cat_n2v_feat: False
    score_num_layers: 2
    product: dot

  Custom_GCN:
    score_in_channels: 32
    score_hidden_channels: 64
    score_num_layers_predictor: 3
    score_dropout: 0.1
    score_out_channels: 1
    score_gin_mlp_layer: 2
    score_cat_node_feat_mf: False
    score_cat_n2v_feat: False
    score_num_layers: 2
    product: inner


  GIN_Variant:
    score_in_channels: 64
    score_hidden_channels: 64
    score_num_layers_predictor: 3
    score_dropout: 0.1
    score_out_channels: 1
    score_gin_mlp_layer: 2
    score_cat_node_feat_mf: False
    score_cat_n2v_feat: False
    score_num_layers: 2
    product: dot

  GraphSAGE:
    score_in_channels: 128
    score_hidden_channels: 64
    score_num_layers_predictor: 3
    score_dropout: 0.1
    score_out_channels: 1
    score_gin_mlp_layer: 2
    score_cat_node_feat_mf: False
    score_cat_n2v_feat: False
    score_num_layers: 2
    product: dot

  LINKX:
    score_in_channels: 64
    score_hidden_channels: 64
    score_num_layers_predictor: 3
    score_dropout: 0.1
    score_out_channels: 1
    score_gin_mlp_layer: 2
    score_cat_node_feat_mf: False
    score_cat_n2v_feat: False
    score_num_layers: 2
    product: dot

num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433
  device: 1
  split_index: [0.8, 0.15, 0.05]

optimizer:
  type: adam
  base_lr: 0.015
  weight_decay: 0.0005

